{% set name = "dash" %}
{% set version = "1.19.0" %}
{% set sha256 = "ba7307f94795fee844551791d401073d4e9b8d71596b37d54e131cec044268ef" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python ==2.7.*|>=3.3
    - setuptools
    - pip
  run:
    - python ==2.7.*|>=3.3
    - pyyaml >=5.1.1
    - flask >=1.0.4
    - flask-compress
    - plotly
    - dash-renderer ==1.9.0
    - dash-core-components ==1.15.0
    - dash-html-components ==1.1.2
    - dash-table ==4.11.2
    - future

test:
  imports:
    - dash.dash
    - dash.dependencies
    - dash.exceptions
    - dash.resources

about:
  home: https://plot.ly/dash
  dev_url: https://github.com/plotly/dash
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python framework for building reactive web-apps.

extra:
  recipe-maintainers:
    - moorepants
