{% set name = "dash" %}
{% set version = "1.13.1" %}
{% set sha256 = "1080ac9386283f91b6b01e653303601cd19ddbdfcb8ce8035f94bf0d35bd57c7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - pyyaml >=5.1.1
    - flask >=1.0.2
    - flask-compress
    - plotly
    - dash-renderer ==1.5.0
    - dash-core-components ==1.10.0
    - dash-html-components ==1.0.3
    - dash-table ==4.8.0
    - future

test:
  imports:
    - dash.dash
    - dash.dependencies
    - dash.exceptions
    - dash.resources

about:
  home: https://plot.ly/dash
  dev_url: https://github.com/plotly/dash
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python framework for building reactive web-apps.

extra:
  recipe-maintainers:
    - moorepants
